In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
%matplotlib inline

In [7]:
hello = tf.constant("Hello ")

In [8]:
world = tf.constant("World !")

In [9]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [10]:
print(hello + world)

Tensor("add:0", shape=(), dtype=string)


In [11]:
tf.Session().run(hello + world)

b'Hello World !'

In [12]:
#2 Next basics

a = tf.constant(10)
b = tf.constant(20)
print (a+b)

Tensor("add_2:0", shape=(), dtype=int32)


In [13]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [17]:
print(result)

30


In [20]:
#3 Next basics

const = tf.constant(10)
fill_mat = tf.fill([4,4],10)
my_zeros = tf.zeros((4,4))
my_ones = tf.ones((4,4))
my_randn = tf.random_normal((4,4))
my_randu = tf.random_uniform((4,4),maxval=1.0)

In [21]:
my_zeros

<tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>

In [22]:
my_operations = [const, fill_mat, my_zeros, my_ones, my_randn, my_randu]

In [23]:
print(my_operations)

[<tf.Tensor 'Const_6:0' shape=() dtype=int32>, <tf.Tensor 'Fill_2:0' shape=(4, 4) dtype=int32>, <tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'ones_1:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]


In [25]:
for op in my_operations:
    print(tf.Session().run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 4.90937591e-01  2.85970330e-01  2.25163072e-01 -7.48984143e-02]
 [ 1.03719378e+00 -4.08118010e-01  2.77150989e-01  6.85405314e-01]
 [-1.08642146e-01 -6.97816253e-01  4.87086922e-01  3.06542218e-01]
 [ 3.54057236e-04 -4.67042327e-01 -7.80663013e-01 -2.94380754e-01]]


[[0.00199211 0.1831168  0.7743827  0.811357  ]
 [0.06359422 0.8754561  0.34932947 0.17912376]
 [0.532235   0.8128061  0.9515743  0.02690172]
 [0.13406742 0.4844967  0.6262032  0.13217175]]




# TensorFlow Graphs