In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
%matplotlib inline

In [7]:
hello = tf.constant("Hello ")

In [8]:
world = tf.constant("World !")

In [9]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [10]:
print(hello + world)

Tensor("add:0", shape=(), dtype=string)


In [11]:
tf.Session().run(hello + world)

b'Hello World !'

In [12]:
#2 Next basics

a = tf.constant(10)
b = tf.constant(20)
print (a+b)

Tensor("add_2:0", shape=(), dtype=int32)


In [13]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [17]:
print(result)

30


In [20]:
#3 Next basics

const = tf.constant(10)
fill_mat = tf.fill([4,4],10)
my_zeros = tf.zeros((4,4))
my_ones = tf.ones((4,4))
my_randn = tf.random_normal((4,4))
my_randu = tf.random_uniform((4,4),maxval=1.0)

In [21]:
my_zeros

<tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>

In [22]:
my_operations = [const, fill_mat, my_zeros, my_ones, my_randn, my_randu]

In [23]:
print(my_operations)

[<tf.Tensor 'Const_6:0' shape=() dtype=int32>, <tf.Tensor 'Fill_2:0' shape=(4, 4) dtype=int32>, <tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'ones_1:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>, <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]


In [25]:
for op in my_operations:
    print(tf.Session().run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 4.90937591e-01  2.85970330e-01  2.25163072e-01 -7.48984143e-02]
 [ 1.03719378e+00 -4.08118010e-01  2.77150989e-01  6.85405314e-01]
 [-1.08642146e-01 -6.97816253e-01  4.87086922e-01  3.06542218e-01]
 [ 3.54057236e-04 -4.67042327e-01 -7.80663013e-01 -2.94380754e-01]]


[[0.00199211 0.1831168  0.7743827  0.811357  ]
 [0.06359422 0.8754561  0.34932947 0.17912376]
 [0.532235   0.8128061  0.9515743  0.02690172]
 [0.13406742 0.4844967  0.6262032  0.13217175]]




# TensorFlow Graphs

In [26]:
#1st example Graph

n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2
#or
n3 = tf.add(n1,n2)

In [28]:
with tf.Session() as sess:
    result = sess.run(n3)

In [29]:
print(result)

3


In [30]:
# Default Graphs of Tensorflow
print (tf.get_default_graph())

In [31]:
# Variables and placeholders in Tensorflow
sess = tf.InteractiveSession()

In [32]:
my_tensor = tf.random_uniform((4,4),0,1)

In [33]:
my_variable = tf.Variable(my_tensor)

In [34]:
print(my_variable)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [36]:
# sess.run(my_variable) This will show error because Global Variable of Graphs are still not initialized

In [37]:
init = tf.global_variables_initializer()

In [38]:
sess.run(init)

In [39]:
sess.run(my_variable)

array([[0.15037894, 0.9130602 , 0.49437535, 0.19750929],
       [0.6988423 , 0.01390958, 0.668345  , 0.514884  ],
       [0.9415567 , 0.10943639, 0.2520696 , 0.5749818 ],
       [0.66100454, 0.693912  , 0.7521236 , 0.9424995 ]], dtype=float32)

In [40]:
# placeholder
ph = tf.placeholder(tf.float32, shape = (None,5))

In [41]:
### Making of First Tensorflow Simple Neural Network

In [42]:
rand_a = np.random.uniform(0,100,(5,5))
rand_b = np.random.uniform(0,100,(5,1))

In [43]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [44]:
add_op = tf.add(a,b)
mult_op = a*b

In [45]:
with tf.Session() as sess:
    add_result = sess.run(add_op, feed_dict={a:10, b:20})
    mult_result = sess.run(mult_op, feed_dict={a:rand_a, b:rand_b})

In [46]:
print(add_result)
print(mult_result)

30.0
[[ 364.6208   334.9059   177.92958  335.43597   59.87462]
 [2023.3163  4870.311   2204.0786  3153.4915  3700.512  ]
 [6088.478   5105.6265  7121.8916  4606.3423  1565.3501 ]
 [1399.7186  1133.3099   448.78308 1519.0154  1272.0394 ]
 [1871.0707  1205.1459  7487.9673  6831.2803  1421.5204 ]]


In [47]:
##### Making a Second Neural Network Graph with many actual features

In [48]:
n_features = 10
n_neurons = 4

In [49]:
x = tf.placeholder(tf.float32,shape = (None, n_features))
m = tf.Variable(initial_value=tf.random_normal(shape=(n_features,n_neurons)))

In [54]:
c = tf.Variable(tf.ones(shape=(n_neurons)))

In [55]:
z = tf.matmul(x,m)
y = tf.add(z,c)

In [59]:
output = tf.sigmoid(y)
init = tf.global_variables_initializer()

In [60]:
with tf.Session() as sess:
    sess.run(init)
    result = sess.run(output, feed_dict={x:np.random.random([1,n_features])})

In [61]:
print(result)

[[0.8904305  0.7165903  0.94449437 0.98127913]]
